Disallow whitespace or comments between an Apos and the following Ident
microsoft/qsharp pull request #418
Opened 2023-06-20 22:31 UTC by sezna

This PR cooks the apostrophe and ident tokens into one new token, `AposIdent`. `AposIdent` represents a generic parameter like `'T`.

closes #407
closes #468

2023-06-21 23:18 UTC, kuzminrobin approved these changes
Approving to unblock. More approvals recommended.

2023-06-21 23:19 UTC, kuzminrobin commented
> Approving to unblock. More approvals recommended.

Looks like it does not help any more. The code owners' approval is still required.

2023-06-22 20:48 UTC, samarsha requested changes

2023-06-22 20:48 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +                }
I wouldn't think of this in terms of the negative cases (it's an error for an Apos to be followed by a Whitespace or Comment). There are lots and lots of negative cases, but there's only one positive case: an Apos token must be followed by an Ident. Let's cook both of them into a single token representing a type parameter name. ([Parse, don't validate.](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/))

This does mean that the name of all type parameters will change downstream to include the `'`, but I think that's fine.

2023-06-27 19:56 UTC, samarsha requested changes

2023-06-27 19:56 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +            TokenKind::AposIdent => f.write_str("`'`"),
This is the token name used in error messages. I would be more descriptive, like:

```suggestion
            TokenKind::AposIdent => f.write_str("apostrophe identifier"),
```

2023-06-27 19:56 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +                Ok(TokenKind::AposIdent)
This treats the identifier after the apostrophe as optional, meaning that an apostrophe followed by a non-ident will still be cooked into AposIdent. There is no other token that uses apostrophe, so it should be an error.

2023-06-28 20:32 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    UnfinishedGeneric(#[label] Span),
This should follow the same pattern as the Incomplete and IncompleteEof errors above.

2023-06-28 20:32 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    UnfinishedGeneric(#[label] Span),
This PR isn’t consistent about whether the token is referred to as an “apostrophe identifier” or a “generic.” I would recommend picking one. The lexer prefers low-level descriptions like apostrophe, while the parser uses high-level descriptions like generic parameter.

2023-06-28 20:32 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +                        .next_if(|t| matches!(t.kind, raw::TokenKind::Ident));
```suggestion
                        .next();
```

2023-07-11 18:15 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    #[error("expected identifier to complete apostrophe identifier, found {0}")]
```suggestion
    #[error("expected identifier after apostrophe, found {0}")]
```

2023-07-11 18:15 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    #[error("expected identifier to complete apostrophe identifier, found EOF")]
```suggestion
    #[error("expected identifier after apostrophe, found EOF")]
```

2023-07-11 18:15 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    IncompleteApostropheIdentifier(raw::TokenKind, #[label] Span),
```suggestion
    #[diagnostic(code("Qsc.Lex.IncompleteAposIdent"))]
    IncompleteAposIdent(raw::TokenKind, #[label] Span),
```

2023-07-11 18:15 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    IncompleteApostropheIdentifierEof(#[label] Span),
```suggestion
    IncompleteAposIdentEof(#[label] Span),
```

2023-07-11 18:15 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    fn single(&mut self, single: Single, span: Span) -> Result<TokenKind, Error> {
`single` doesn't need this parameter. The other incomplete errors use the span of the next token, not the span of the current token.

2023-07-12 17:10 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    IncompleteAposIdentEof(#[label] Span),
nit: Can you move these up so all the `Incomplete*` cases are next to each other?

2023-07-13 17:08 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifier"))]
```suggestion
    #[diagnostic(code("Qsc.Lex.IncompleteAposIdent"))]
```

2023-07-13 17:08 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifierEof"))]
```suggestion
    #[diagnostic(code("Qsc.Lex.IncompleteAposIdentEof"))]
```

2023-07-13 23:59 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
> +            }
I don't think we should just copy/paste this from Lexer::expect - handling any Token is more general than handling only Single tokens, so there should be a way to refactor and share the logic.

2023-07-17 22:45 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
>      #[error("expected `{0}` to complete {1}, found {2}")]
The Display for raw::TokenKind already puts ticks around Single.

```suggestion
    #[error("expected {0} to complete {1}, found {2}")]
```

2023-07-17 22:45 UTC, samarsha commented on compiler/qsc_parse/src/lex/cooked.rs
>      #[error("expected `{0}` to complete {1}, found EOF")]
```suggestion
    #[error("expected {0} to complete {1}, found EOF")]
```

2023-07-18 18:24 UTC, samarsha commented
The tests need to be updated, but I think the new spans in the errors are correct.

2023-07-18 20:59 UTC, samarsha approved these changes

2023-07-18 21:56 UTC, merged